### ISSUE TITLE
non-mapbox workshops

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/workshops#13]
Could we include on the list Mapbox workshops put together by other people? eg. https://sites.google.com/view/mapbox-decompress-2018/home

cc @jinalfoflia

**Comment by jinalfoflia** [comment]
This is a great idea @andrewharvey! I have added a [section](https://github.com/mapbox/workshops/blob/gh-pages/README.md#mapbox-workshops-by-the-community) for the same, to begin with, it'll be awesome if you could add the workshop you suggested with a short description of it.

**Comment by andrewharvey** [comment]
Perfect!
